version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  worker:
    build: .
    command: celery -A src.worker.celery_app worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
      - .env
